# Generated by Django 4.1.7 on 2023-09-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazardreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='address',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='pin_code',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
