# Generated by Django 4.1.7 on 2023-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazardreports', '0002_hazardreport_address_hazardreport_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
